site_name: alfredo
repo_url: https://github.com/fcarli/alfredo
site_url: https://fcarli.github.io/alfredo
site_description: Python harness for  AI agents
site_author: Francesco Carli
edit_uri: edit/main/docs/
repo_name: fcarli/alfredo
copyright: Maintained by <a href="https://fcarli.com">fcarli</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/alfredo"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fcarli/alfredo
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/alfredo

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
